### ISSUE TITLE
Error "Object Reference Not Set to an Instance of an Object" on login

### ISSUE THREAD

**Issue by ThomasRossmeisl** [coolOrangeLabs/powerflc-explorer-extension#1]
Description
=======
When logging into Vault the error "Object Reference Not Set to an Instance of an Object" is displayed.
Message in german: "Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt"
![image](https://user-images.githubusercontent.com/34453713/169022699-7c57737c-84a0-413f-b08a-8ff157589253.png)

The customer has following coolOrange products installed and only after installing powerFLC_ExplorerExtension_Vault2022_1.0.14.msi the error occurrs.
![image](https://user-images.githubusercontent.com/34453713/169022634-0bbea026-7aaa-4ef0-bc3b-ef4a70105de0.png)

Steps
====
* Install all the coolOrange products except the powerflc-explorer-extension
* Start Vault and login to verify no error appears
* Install powerflc-explorer-extension
* Start Vault and login 

Affected Versions
===========
* 1.0.14.0 for Vault 2022

Remarks
======
* Steps to reproduce were tested on the customers system only

**Comment by christiangessner** [comment]
Fixed with commit https://github.com/coolOrangeLabs/powerflc-explorer-extension/commit/493f4535586a0b3a29993e4e3cc5b3243e4f5de0
